// teste1/src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Providers from "./components/Providers";
import { AppProvider } from "../context/AppContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> {/* Agora o SessionProvider envolve toda a árvore */}
          <AppProvider>
            <div className="flex w-full">
              <div className="min-w-[200px]">
                <Navbar />
              </div>
              <div className="w-full">{children}</div>
            </div>
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}
